sudo: false
language: node_js
node_js:
- '10'
cache:
directories:
- node_modules
before_install:
- npm update
install:
- cd C:/Users/Sania/github_frontend+js_2018-2019/HW6/package.json
- npm install
script:
- npm test